// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/location_event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LocationEvent is the schema for GPS events flowing through the Kafka topic.
//
// Using Protobuf instead of raw JSON gives us:
//   - Schema enforcement: producer and consumer can't silently diverge
//   - ~40% smaller payloads vs JSON (no field name repetition)
//   - Versioning: new fields are backward-compatible with older consumers
//   - A schema registry story: this .proto file IS the contract
//
// The event_id field doubles as the Cassandra idempotency key (improvement #5).
// recorded_at is Unix milliseconds to avoid timestamp parsing overhead.
type LocationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`        // UUID string — Kafka partition key
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`                                // WGS-84 latitude  (-90..90)
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`                                // WGS-84 longitude (-180..180)
	Speed         float32                `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`                            // km/h
	RecordedAt    int64                  `protobuf:"varint,5,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"` // Unix milliseconds UTC
	EventId       string                 `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`           // UUID — idempotency key for Cassandra
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationEvent) Reset() {
	*x = LocationEvent{}
	mi := &file_proto_location_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationEvent) ProtoMessage() {}

func (x *LocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationEvent.ProtoReflect.Descriptor instead.
func (*LocationEvent) Descriptor() ([]byte, []int) {
	return file_proto_location_event_proto_rawDescGZIP(), []int{0}
}

func (x *LocationEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *LocationEvent) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LocationEvent) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *LocationEvent) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationEvent) GetRecordedAt() int64 {
	if x != nil {
		return x.RecordedAt
	}
	return 0
}

func (x *LocationEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_proto_location_event_proto protoreflect.FileDescriptor

const file_proto_location_event_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/location_event.proto\x12\x0flocationtracker\"\xa2\x01\n" +
	"\rLocationEvent\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x02R\x05speed\x12\x1f\n" +
	"\vrecorded_at\x18\x05 \x01(\x03R\n" +
	"recordedAt\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\tR\aeventIdB*Z(github.com/pranav/location-tracker/protob\x06proto3"

var (
	file_proto_location_event_proto_rawDescOnce sync.Once
	file_proto_location_event_proto_rawDescData []byte
)

func file_proto_location_event_proto_rawDescGZIP() []byte {
	file_proto_location_event_proto_rawDescOnce.Do(func() {
		file_proto_location_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_event_proto_rawDesc), len(file_proto_location_event_proto_rawDesc)))
	})
	return file_proto_location_event_proto_rawDescData
}

var file_proto_location_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_location_event_proto_goTypes = []any{
	(*LocationEvent)(nil), // 0: locationtracker.LocationEvent
}
var file_proto_location_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_location_event_proto_init() }
func file_proto_location_event_proto_init() {
	if File_proto_location_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_event_proto_rawDesc), len(file_proto_location_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_location_event_proto_goTypes,
		DependencyIndexes: file_proto_location_event_proto_depIdxs,
		MessageInfos:      file_proto_location_event_proto_msgTypes,
	}.Build()
	File_proto_location_event_proto = out.File
	file_proto_location_event_proto_goTypes = nil
	file_proto_location_event_proto_depIdxs = nil
}
